server:
  port: 8888
  servlet:
    context-path: /course

# spring相关配置  datasource数据源  thymeleaf模版引擎
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scoremanage?useUnicode=true&charcterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456789
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  mqtt:
    username: admin
    password: 123456
    url: tcp://localhost:1883
    client:
      id:  mqttClientId
    default:
      topic:  test/topic
    completionTimeout: 30000


#  web:
#    resources:
#      static-locations: classpath:/static/
#  mvc:
#    static-path-pattern: /static/**

# Mybatis配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.hbgc.course.admin.po
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    root: info
    com.hbgc.course.admin: debug
    org:
       springframework:
          integration:
            mqtt: DEBUG
